### ISSUE TITLE
[bug/question] Uncaught ReferenceError: nw is not defined

### ISSUE THREAD

**Issue by JhonnyJason** [englishextra/qrjs2#9]
### Checklist
* My **browser** is: Chromium Version 89.0.4389.114
* I'm using version 0.1.8

### Description
I bundle my project using webpack 5.
So for using the package from within my code I would go for:
```
var qrGenerator = require("qr2js")
```
```
import qrGenerator from "qrjs2"
```
### Expected behavior
Having the Module available as `qrGenerator` in my code such that I could use it like
```
var qrSvg = qrGenerator.generateSVG(information, options)
```

### Actual behavior
Instant error when loading.
```
Uncaught ReferenceError: nw is not defined
    at eval (main.js:6)
    at Object../node_modules/qrjs2/main.js ((index):1781)
    at __webpack_require__ ((index):2300)
    at eval (qrdisplaymodule.js:2)
    at Module../toolset/build/js/qrdisplaymodule.js ((index):2126)
    at __webpack_require__ ((index):2300)
    at eval (allmodules.js:37)
    at Module../toolset/build/js/allmodules.js ((index):1942)
    at __webpack_require__ ((index):2300)
    at eval (index.js:2)
```

I'm sure it's specifically a bundling issue there.
Maybe there is a quick fix to have this awesome package bundleable this way :-)

Cheers!

**Comment by englishextra** [comment]
You shouldn't use `main.js` - it's for launching the `index.html` with `nwjs` instead of using `http-server`

This is not in the scope of the project. I use `main.js` as well as `index.js` to launch demo, so that to quickly see if the library works fine.

```batch
start "" "G:\server\apps\nwjs-sdk-win-x64\nw.exe" "./"
```
and

```batch
start "" "G:\server\apps\electron-win32-x64\electron.exe" "./index.js"
```

as you can see I have binaries of `Electron` and `NWJS` on my hard drive.

This repo hasn't been aimed at using specifically `webpack`.

So perhaps you will have to revise main.js or delete it.

The property

```json
"main": "main.js",
```
in `package.json` is for the above mentioned purpose, and not for using the library — it's for local testing.

I guess `webpack` takes this property, considering it is specially designed for `webpack`-ing.

**Comment by JhonnyJason** [comment]
Yhea that seems like being the issue, thank you for the hint! 

I will check how I could adjust that for package deployment and webpack bundling.
Cheers!

**Comment by shulhi** [comment]
> Yhea that seems like being the issue, thank you for the hint!
> 
> I will check how I could adjust that for package deployment and webpack bundling.
> Cheers!

did you able to get it working with webpack?

**Comment by JhonnyJason** [comment]
@shulhi No I did use another package as quickfix then - however happy to use this package if you did that - as I prefer svg :sunglasses:
 
I will also give an update here when I finally have managed to do it xD
Cheers!

**Comment by englishextra** [comment]
@shulhi @JhonnyJason 

in new version 0.1.9 which is published to npm
in `package.json`

```json
"main": "js/qrjs2.js",
```

so I hope this will help with `webpack` issue
